version: '3.8'

networks:
  three:

services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
    #  - '443:443'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - 'certs:/etc/nginx/certs:ro'
      - 'vhostd:/etc/nginx/vhost.d'
      - 'html:/usr/share/nginx/html'
    networks:
      - three
    # labels:
    #   - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    
# letsencrypt:
#   image: nginxproxy/acme-companion
#   environment:
#     - NGINX_PROXY_CONTAINER=nginx-proxy
#     - ACME_CA_URI=https://acme-staging-v02.api.letsencrypt.org/directory
#   volumes:
#     - 'certs:/etc/nginx/certs:rw'
#     - 'vhostd:/etc/nginx/vhost.d'
#     - 'html:/usr/share/nginx/html'
#     - '/var/run/docker.sock:/var/run/docker.sock:ro'
  
  three-service:
    image: docker.jesusyaro.com/three
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: three-container
    expose:
      - '80'
    networks:
      - three
    environment:
      - VIRTUAL_HOST=localhost
      - LETSENCRYPT_HOST=localhost
      - LETSENCRYPT_EMAIL=jesusaleyaro@hotmail.com  

volumes:
  certs: null
  html: null
  vhostd: null